quarkus.http.port=${PORT:8080}

# CatFacts
quarkus.rest-client.catFacts-api.url=https://catfact.ninja/fact
quarkus.rest-client.catFacts-api.scope=javax.inject.Singleton

# Participation Plugin
quarkus.rest-client.participationPlugin-api.url=https://iota-node.tanglebay.com
quarkus.rest-client.participationPlugin-api.scope=javax.inject.Singleton