# Quarkus settings
quarkus.http.port=${PORT:8080}
quarkus.log.category."org.apache.http".level=DEBUG
quarkus.quinoa.dev-server.port=3000
quarkus.rest.path=/api
quarkus.http.filter.others.header.Cache-Control=no-cache
quarkus.http.filter.others.matches=/.*
quarkus.http.filter.others.methods=GET
quarkus.http.filter.others.order=0
quarkus.http.filter.static.header.Cache-Control=max-age=31536000
quarkus.http.filter.static.matches=/static/.+
quarkus.http.filter.static.methods=GET
quarkus.http.filter.static.order=1

# Postgres SQL DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=${DATABASE_URL:postgres://postgres:postgrespw@localhost:49155/postgres}
quarkus.hibernate-orm.database.generation=drop-and-create

# Participation Plugin
quarkus.rest-client.participationPlugin-api.url=https://iota-node.tanglebay.com
quarkus.rest-client.participationPlugin-api.scope=javax.inject.Singleton